### ISSUE TITLE
C/C++ support

### ISSUE THREAD

**Issue by ThomasCluzel** [cnescatlab/sonar-scanner-catlab#9]
#### Is your feature request related to a problem? Please describe.

> _A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

C/C++ languages should be supported.

#### Describe the solution you'd like

> _A clear and concise description of what you want to happen._

The same tools as in Docker-CAT should be available.

#### Describe alternatives you've considered

> _A clear and concise description of any alternative solutions or features you've considered._

**Comment by pratik376** [comment]
Is your feature request related to a problem? Please describe.

A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

C/C++ languages should be supported.

Describe the solution you'd like

A clear and concise description of what you want to happen.

The same tools as in Docker-CAT should be available.

Describe alternatives you've considered

A clear and concise description of any alternative solutions or features you've considered.
